# Generated by Django 5.0.6 on 2024-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('idEquipment', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cantity', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(0, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idEquipment', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cantity', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ppe',
            fields=[
                ('idPpe', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('cantity', models.IntegerField(default=0)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('idTool', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cantity', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(0, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('idWorker', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
    ]
