# Generated by Django 5.0.6 on 2024-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_equipment_name_alter_material_cantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppe',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
