# Generated by Django 5.0.6 on 2024-06-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_rename_cantity_ppe_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='cantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='cantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='cantity',
            new_name='quantity',
        ),
    ]
