# Generated by Django 5.0.6 on 2024-06-15 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_rename_cantity_equipment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='level',
            field=models.IntegerField(choices=[(0, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=0, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cos'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='unitCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='level',
            field=models.IntegerField(choices=[(0, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=0, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Apellido'),
        ),
    ]
