# Generated by Django 5.0.6 on 2024-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_equipment_level_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
