# Generated by Django 5.0.6 on 2024-06-18 03:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_alter_equipment_level_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='idEquipment',
            new_name='idMaterial',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='idWorker',
        ),
        migrations.AddField(
            model_name='ppe',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='contractDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worker',
            name='dni',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='idEquipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment'),
        ),
        migrations.AddField(
            model_name='worker',
            name='idMaterials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material'),
        ),
        migrations.AddField(
            model_name='worker',
            name='idPpe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.ppe'),
        ),
        migrations.AddField(
            model_name='worker',
            name='idTool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.tool'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(default=None, max_length=20, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
