# Generated by Django 5.0.6 on 2024-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_equipment_archivo_alter_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
