# Generated by Django 5.0.6 on 2024-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_material_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo'),
        ),
    ]
