# Generated by Django 5.0.6 on 2024-06-19 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_worker_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
