# Generated by Django 5.0.6 on 2024-06-19 20:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_alter_equipment_name_alter_equipment_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='idEquipment',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='idMaterials',
            new_name='materials',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='idPpe',
            new_name='ppe',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='idTool',
            new_name='tool',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='idWorker',
            new_name='worker',
        ),
        migrations.AlterField(
            model_name='loan',
            name='idLoan',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returnLoanDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución'),
        ),
    ]
