# Generated by Django 5.0.6 on 2024-06-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_rename_idequipment_loan_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='materials',
            new_name='material',
        ),
    ]
