# Generated by Django 5.0.6 on 2024-06-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_rename_materials_loan_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
