# Generated by Django 5.0.6 on 2024-06-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_alter_ppe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
    ]
